### ISSUE TITLE
vue-router 테스팅에 관해서..

### ISSUE THREAD

**Issue by leehan0617** [MartinYounghoonKim/vuejs-todo-unit-test#1]
혹시 vue-router에 관련된 테스팅은 어떻게 하시는지 궁금합니다..
감사합니다

**Comment by MartinYounghoonKim** [comment]
@leehan0617 
단위테스트에 대해서 말씀이신가요 ?
현재 이슈로 남겨주신 프로젝트에는 vue-router 가 붙여있지 않아, 실무에서 진행 중인 것을 기준으로 저 같은 경우는 단위 테스트는 컴포넌트나 서비스 레이어 그리고 vuex 정도에서만 하고 있습니다.
